package com.dtkq.api.dao;

import com.dtkq.api.entity.DoctorClass;
import java.util.List;

public interface DoctorClassMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_class
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_class
     *
     * @mbg.generated
     */
    int insert(DoctorClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_class
     *
     * @mbg.generated
     */
    DoctorClass selectByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_class
     *
     * @mbg.generated
     */
    List<DoctorClass> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DoctorClass record);
}