package com.dtkq.api.dao;

import com.dtkq.api.entity.TopImg;
import java.util.List;

public interface TopImgMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_img
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_img
     *
     * @mbg.generated
     */
    int insert(TopImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_img
     *
     * @mbg.generated
     */
    TopImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_img
     *
     * @mbg.generated
     */
    List<TopImg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TopImg record);
}