package com.dtkq.api.dao;

import com.dtkq.api.entity.TopMenu;
import java.util.List;

public interface TopMenuMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_menu
     *
     * @mbg.generated
     */
    int insert(TopMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_menu
     *
     * @mbg.generated
     */
    TopMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_menu
     *
     * @mbg.generated
     */
    List<TopMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TopMenu record);
}