package com.dtkq.api.entity;

import java.io.Serializable;
import java.util.Date;

public class AdminAuth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.auth_name
     *
     * @mbg.generated
     */
    private String authName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_auth
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.id
     *
     * @return the value of admin_auth.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.id
     *
     * @param id the value for admin_auth.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.auth_name
     *
     * @return the value of admin_auth.auth_name
     *
     * @mbg.generated
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.auth_name
     *
     * @param authName the value for admin_auth.auth_name
     *
     * @mbg.generated
     */
    public void setAuthName(String authName) {
        this.authName = authName == null ? null : authName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.ctime
     *
     * @return the value of admin_auth.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.ctime
     *
     * @param ctime the value for admin_auth.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", authName=").append(authName);
        sb.append(", ctime=").append(ctime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}