package com.dtkq.api.entity;

import java.io.Serializable;

public class Article implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_id
     *
     * @mbg.generated
     */
    private Integer artId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.class_id
     *
     * @mbg.generated
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_user_id
     *
     * @mbg.generated
     */
    private Integer artUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_title
     *
     * @mbg.generated
     */
    private String artTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_img
     *
     * @mbg.generated
     */
    private String artImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_vedio
     *
     * @mbg.generated
     */
    private String artVedio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.cime
     *
     * @mbg.generated
     */
    private String cime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.label
     *
     * @mbg.generated
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.art_content
     *
     * @mbg.generated
     */
    private String artContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_id
     *
     * @return the value of article.art_id
     *
     * @mbg.generated
     */
    public Integer getArtId() {
        return artId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_id
     *
     * @param artId the value for article.art_id
     *
     * @mbg.generated
     */
    public void setArtId(Integer artId) {
        this.artId = artId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.class_id
     *
     * @return the value of article.class_id
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.class_id
     *
     * @param classId the value for article.class_id
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_user_id
     *
     * @return the value of article.art_user_id
     *
     * @mbg.generated
     */
    public Integer getArtUserId() {
        return artUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_user_id
     *
     * @param artUserId the value for article.art_user_id
     *
     * @mbg.generated
     */
    public void setArtUserId(Integer artUserId) {
        this.artUserId = artUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_title
     *
     * @return the value of article.art_title
     *
     * @mbg.generated
     */
    public String getArtTitle() {
        return artTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_title
     *
     * @param artTitle the value for article.art_title
     *
     * @mbg.generated
     */
    public void setArtTitle(String artTitle) {
        this.artTitle = artTitle == null ? null : artTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_img
     *
     * @return the value of article.art_img
     *
     * @mbg.generated
     */
    public String getArtImg() {
        return artImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_img
     *
     * @param artImg the value for article.art_img
     *
     * @mbg.generated
     */
    public void setArtImg(String artImg) {
        this.artImg = artImg == null ? null : artImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_vedio
     *
     * @return the value of article.art_vedio
     *
     * @mbg.generated
     */
    public String getArtVedio() {
        return artVedio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_vedio
     *
     * @param artVedio the value for article.art_vedio
     *
     * @mbg.generated
     */
    public void setArtVedio(String artVedio) {
        this.artVedio = artVedio == null ? null : artVedio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.cime
     *
     * @return the value of article.cime
     *
     * @mbg.generated
     */
    public String getCime() {
        return cime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.cime
     *
     * @param cime the value for article.cime
     *
     * @mbg.generated
     */
    public void setCime(String cime) {
        this.cime = cime == null ? null : cime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.status
     *
     * @return the value of article.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.status
     *
     * @param status the value for article.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.label
     *
     * @return the value of article.label
     *
     * @mbg.generated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.label
     *
     * @param label the value for article.label
     *
     * @mbg.generated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.art_content
     *
     * @return the value of article.art_content
     *
     * @mbg.generated
     */
    public String getArtContent() {
        return artContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.art_content
     *
     * @param artContent the value for article.art_content
     *
     * @mbg.generated
     */
    public void setArtContent(String artContent) {
        this.artContent = artContent == null ? null : artContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", artId=").append(artId);
        sb.append(", classId=").append(classId);
        sb.append(", artUserId=").append(artUserId);
        sb.append(", artTitle=").append(artTitle);
        sb.append(", artImg=").append(artImg);
        sb.append(", artVedio=").append(artVedio);
        sb.append(", cime=").append(cime);
        sb.append(", status=").append(status);
        sb.append(", label=").append(label);
        sb.append(", artContent=").append(artContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}