package com.dtkq.api.entity;

import java.io.Serializable;
import java.util.Date;

public class Ask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.ask_id
     *
     * @mbg.generated
     */
    private Integer askId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.class_id
     *
     * @mbg.generated
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.ask_user_id
     *
     * @mbg.generated
     */
    private Integer askUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.ask_title
     *
     * @mbg.generated
     */
    private String askTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.ask_img
     *
     * @mbg.generated
     */
    private String askImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.ask_vedio
     *
     * @mbg.generated
     */
    private String askVedio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.label
     *
     * @mbg.generated
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.ask_content
     *
     * @mbg.generated
     */
    private String askContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ask
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.ask_id
     *
     * @return the value of ask.ask_id
     *
     * @mbg.generated
     */
    public Integer getAskId() {
        return askId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.ask_id
     *
     * @param askId the value for ask.ask_id
     *
     * @mbg.generated
     */
    public void setAskId(Integer askId) {
        this.askId = askId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.class_id
     *
     * @return the value of ask.class_id
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.class_id
     *
     * @param classId the value for ask.class_id
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.ask_user_id
     *
     * @return the value of ask.ask_user_id
     *
     * @mbg.generated
     */
    public Integer getAskUserId() {
        return askUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.ask_user_id
     *
     * @param askUserId the value for ask.ask_user_id
     *
     * @mbg.generated
     */
    public void setAskUserId(Integer askUserId) {
        this.askUserId = askUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.ask_title
     *
     * @return the value of ask.ask_title
     *
     * @mbg.generated
     */
    public String getAskTitle() {
        return askTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.ask_title
     *
     * @param askTitle the value for ask.ask_title
     *
     * @mbg.generated
     */
    public void setAskTitle(String askTitle) {
        this.askTitle = askTitle == null ? null : askTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.ask_img
     *
     * @return the value of ask.ask_img
     *
     * @mbg.generated
     */
    public String getAskImg() {
        return askImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.ask_img
     *
     * @param askImg the value for ask.ask_img
     *
     * @mbg.generated
     */
    public void setAskImg(String askImg) {
        this.askImg = askImg == null ? null : askImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.ask_vedio
     *
     * @return the value of ask.ask_vedio
     *
     * @mbg.generated
     */
    public String getAskVedio() {
        return askVedio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.ask_vedio
     *
     * @param askVedio the value for ask.ask_vedio
     *
     * @mbg.generated
     */
    public void setAskVedio(String askVedio) {
        this.askVedio = askVedio == null ? null : askVedio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.ctime
     *
     * @return the value of ask.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.ctime
     *
     * @param ctime the value for ask.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.status
     *
     * @return the value of ask.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.status
     *
     * @param status the value for ask.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.label
     *
     * @return the value of ask.label
     *
     * @mbg.generated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.label
     *
     * @param label the value for ask.label
     *
     * @mbg.generated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.ask_content
     *
     * @return the value of ask.ask_content
     *
     * @mbg.generated
     */
    public String getAskContent() {
        return askContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.ask_content
     *
     * @param askContent the value for ask.ask_content
     *
     * @mbg.generated
     */
    public void setAskContent(String askContent) {
        this.askContent = askContent == null ? null : askContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", askId=").append(askId);
        sb.append(", classId=").append(classId);
        sb.append(", askUserId=").append(askUserId);
        sb.append(", askTitle=").append(askTitle);
        sb.append(", askImg=").append(askImg);
        sb.append(", askVedio=").append(askVedio);
        sb.append(", ctime=").append(ctime);
        sb.append(", status=").append(status);
        sb.append(", label=").append(label);
        sb.append(", askContent=").append(askContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}