package com.dtkq.api.entity;

import java.io.Serializable;
import java.util.Date;

public class AskThumbs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask_thumbs.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask_thumbs.ask_id
     *
     * @mbg.generated
     */
    private Integer askId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask_thumbs.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask_thumbs.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask_thumbs.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ask_thumbs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask_thumbs.id
     *
     * @return the value of ask_thumbs.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask_thumbs.id
     *
     * @param id the value for ask_thumbs.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask_thumbs.ask_id
     *
     * @return the value of ask_thumbs.ask_id
     *
     * @mbg.generated
     */
    public Integer getAskId() {
        return askId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask_thumbs.ask_id
     *
     * @param askId the value for ask_thumbs.ask_id
     *
     * @mbg.generated
     */
    public void setAskId(Integer askId) {
        this.askId = askId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask_thumbs.user_id
     *
     * @return the value of ask_thumbs.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask_thumbs.user_id
     *
     * @param userId the value for ask_thumbs.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask_thumbs.ctime
     *
     * @return the value of ask_thumbs.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask_thumbs.ctime
     *
     * @param ctime the value for ask_thumbs.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask_thumbs.status
     *
     * @return the value of ask_thumbs.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask_thumbs.status
     *
     * @param status the value for ask_thumbs.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_thumbs
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", askId=").append(askId);
        sb.append(", userId=").append(userId);
        sb.append(", ctime=").append(ctime);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}