package com.dtkq.api.entity;

import java.io.Serializable;
import java.util.Date;

public class DoctorClass implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_class.class_id
     *
     * @mbg.generated
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_class.class_ch_name
     *
     * @mbg.generated
     */
    private String classChName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_class.class_en_name
     *
     * @mbg.generated
     */
    private String classEnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_class.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_class.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor_class
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_class.class_id
     *
     * @return the value of doctor_class.class_id
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_class.class_id
     *
     * @param classId the value for doctor_class.class_id
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_class.class_ch_name
     *
     * @return the value of doctor_class.class_ch_name
     *
     * @mbg.generated
     */
    public String getClassChName() {
        return classChName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_class.class_ch_name
     *
     * @param classChName the value for doctor_class.class_ch_name
     *
     * @mbg.generated
     */
    public void setClassChName(String classChName) {
        this.classChName = classChName == null ? null : classChName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_class.class_en_name
     *
     * @return the value of doctor_class.class_en_name
     *
     * @mbg.generated
     */
    public String getClassEnName() {
        return classEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_class.class_en_name
     *
     * @param classEnName the value for doctor_class.class_en_name
     *
     * @mbg.generated
     */
    public void setClassEnName(String classEnName) {
        this.classEnName = classEnName == null ? null : classEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_class.ctime
     *
     * @return the value of doctor_class.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_class.ctime
     *
     * @param ctime the value for doctor_class.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_class.status
     *
     * @return the value of doctor_class.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_class.status
     *
     * @param status the value for doctor_class.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_class
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", classId=").append(classId);
        sb.append(", classChName=").append(classChName);
        sb.append(", classEnName=").append(classEnName);
        sb.append(", ctime=").append(ctime);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}