package com.dtkq.api.entity;

import java.io.Serializable;
import java.util.Date;

public class DoctorTimeBook implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_time_book.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_time_book.time_id
     *
     * @mbg.generated
     */
    private Integer timeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_time_book.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_time_book.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_time_book.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_time_book.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor_time_book
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_time_book.id
     *
     * @return the value of doctor_time_book.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_time_book.id
     *
     * @param id the value for doctor_time_book.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_time_book.time_id
     *
     * @return the value of doctor_time_book.time_id
     *
     * @mbg.generated
     */
    public Integer getTimeId() {
        return timeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_time_book.time_id
     *
     * @param timeId the value for doctor_time_book.time_id
     *
     * @mbg.generated
     */
    public void setTimeId(Integer timeId) {
        this.timeId = timeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_time_book.user_id
     *
     * @return the value of doctor_time_book.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_time_book.user_id
     *
     * @param userId the value for doctor_time_book.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_time_book.remark
     *
     * @return the value of doctor_time_book.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_time_book.remark
     *
     * @param remark the value for doctor_time_book.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_time_book.ctime
     *
     * @return the value of doctor_time_book.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_time_book.ctime
     *
     * @param ctime the value for doctor_time_book.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_time_book.status
     *
     * @return the value of doctor_time_book.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_time_book.status
     *
     * @param status the value for doctor_time_book.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_time_book
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", timeId=").append(timeId);
        sb.append(", userId=").append(userId);
        sb.append(", remark=").append(remark);
        sb.append(", ctime=").append(ctime);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}