package com.dtkq.api.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class TalkClass implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_class.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_class.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_class.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_class.ch_name
     *
     * @mbg.generated
     */
    private String chName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_class.en_name
     *
     * @mbg.generated
     */
    private String enName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_class.auth
     *
     * @mbg.generated
     */
    private Integer auth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_class.ctime
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT+8"
    )
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_class.style
     *
     * @mbg.generated
     */
    private Integer style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_class.status
     *
     * @mbg.generated
     */
    private Integer status;

    private List<TalkClass> sonList;

    private List<ClassObj> classObjList;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table talk_class
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_class.id
     *
     * @return the value of talk_class.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_class.id
     *
     * @param id the value for talk_class.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_class.level
     *
     * @return the value of talk_class.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_class.level
     *
     * @param level the value for talk_class.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_class.parent_id
     *
     * @return the value of talk_class.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_class.parent_id
     *
     * @param parentId the value for talk_class.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_class.ch_name
     *
     * @return the value of talk_class.ch_name
     *
     * @mbg.generated
     */
    public String getChName() {
        return chName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_class.ch_name
     *
     * @param chName the value for talk_class.ch_name
     *
     * @mbg.generated
     */
    public void setChName(String chName) {
        this.chName = chName == null ? null : chName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_class.en_name
     *
     * @return the value of talk_class.en_name
     *
     * @mbg.generated
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_class.en_name
     *
     * @param enName the value for talk_class.en_name
     *
     * @mbg.generated
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_class.auth
     *
     * @return the value of talk_class.auth
     *
     * @mbg.generated
     */
    public Integer getAuth() {
        return auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_class.auth
     *
     * @param auth the value for talk_class.auth
     *
     * @mbg.generated
     */
    public void setAuth(Integer auth) {
        this.auth = auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_class.ctime
     *
     * @return the value of talk_class.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_class.ctime
     *
     * @param ctime the value for talk_class.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_class.style
     *
     * @return the value of talk_class.style
     *
     * @mbg.generated
     */
    public Integer getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_class.style
     *
     * @param style the value for talk_class.style
     *
     * @mbg.generated
     */
    public void setStyle(Integer style) {
        this.style = style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_class.status
     *
     * @return the value of talk_class.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_class.status
     *
     * @param status the value for talk_class.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public List<TalkClass> getSonList() {
        return sonList;
    }

    public void setSonList(List<TalkClass> sonList) {
        this.sonList = sonList;
    }

    public List<ClassObj> getClassObjList() {
        return classObjList;
    }

    public void setClassObjList(List<ClassObj> classObjList) {
        this.classObjList = classObjList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_class
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", level=").append(level);
        sb.append(", parentId=").append(parentId);
        sb.append(", chName=").append(chName);
        sb.append(", enName=").append(enName);
        sb.append(", auth=").append(auth);
        sb.append(", ctime=").append(ctime);
        sb.append(", style=").append(style);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}