package com.dtkq.api.entity;

import java.io.Serializable;
import java.util.Date;

public class TopImg implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column top_img.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column top_img.bg_img
     *
     * @mbg.generated
     */
    private String bgImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column top_img.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column top_img.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table top_img
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column top_img.id
     *
     * @return the value of top_img.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column top_img.id
     *
     * @param id the value for top_img.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column top_img.bg_img
     *
     * @return the value of top_img.bg_img
     *
     * @mbg.generated
     */
    public String getBgImg() {
        return bgImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column top_img.bg_img
     *
     * @param bgImg the value for top_img.bg_img
     *
     * @mbg.generated
     */
    public void setBgImg(String bgImg) {
        this.bgImg = bgImg == null ? null : bgImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column top_img.status
     *
     * @return the value of top_img.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column top_img.status
     *
     * @param status the value for top_img.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column top_img.ctime
     *
     * @return the value of top_img.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column top_img.ctime
     *
     * @param ctime the value for top_img.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_img
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bgImg=").append(bgImg);
        sb.append(", status=").append(status);
        sb.append(", ctime=").append(ctime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}