package com.dtkq.api.entity;

import java.io.Serializable;
import java.util.Date;

public class UserTalkRead implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_talk_read.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_talk_read.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_talk_read.talk_id
     *
     * @mbg.generated
     */
    private Integer talkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_talk_read.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_talk_read
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_talk_read.id
     *
     * @return the value of user_talk_read.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_talk_read.id
     *
     * @param id the value for user_talk_read.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_talk_read.user_id
     *
     * @return the value of user_talk_read.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_talk_read.user_id
     *
     * @param userId the value for user_talk_read.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_talk_read.talk_id
     *
     * @return the value of user_talk_read.talk_id
     *
     * @mbg.generated
     */
    public Integer getTalkId() {
        return talkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_talk_read.talk_id
     *
     * @param talkId the value for user_talk_read.talk_id
     *
     * @mbg.generated
     */
    public void setTalkId(Integer talkId) {
        this.talkId = talkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_talk_read.ctime
     *
     * @return the value of user_talk_read.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_talk_read.ctime
     *
     * @param ctime the value for user_talk_read.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_talk_read
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", talkId=").append(talkId);
        sb.append(", ctime=").append(ctime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}