package com.dtkq.api.mapper;

import com.dtkq.api.entity.AdminAuth;
import java.util.List;

public interface AdminAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated
     */
    int insert(AdminAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated
     */
    AdminAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated
     */
    List<AdminAuth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminAuth record);
}