package com.dtkq.api.mapper;

import com.dtkq.api.entity.ArticleThumbs;
import java.util.List;

public interface ArticleThumbsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_thumbs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_thumbs
     *
     * @mbg.generated
     */
    int insert(ArticleThumbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_thumbs
     *
     * @mbg.generated
     */
    ArticleThumbs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_thumbs
     *
     * @mbg.generated
     */
    List<ArticleThumbs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_thumbs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleThumbs record);
}