package com.dtkq.api.mapper;

import com.dtkq.api.entity.AskAnswer;
import java.util.List;

public interface AskAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_answer
     *
     * @mbg.generated
     */
    int insert(AskAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_answer
     *
     * @mbg.generated
     */
    AskAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_answer
     *
     * @mbg.generated
     */
    List<AskAnswer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AskAnswer record);
}