package com.dtkq.api.mapper;

import com.dtkq.api.entity.AskComment;
import java.util.List;

public interface AskCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_comment
     *
     * @mbg.generated
     */
    int insert(AskComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_comment
     *
     * @mbg.generated
     */
    AskComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_comment
     *
     * @mbg.generated
     */
    List<AskComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AskComment record);
}