package com.dtkq.api.mapper;

import com.dtkq.api.entity.Ask;
import java.util.List;

public interface AskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer askId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated
     */
    int insert(Ask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated
     */
    Ask selectByPrimaryKey(Integer askId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated
     */
    List<Ask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ask record);
}