package com.dtkq.api.mapper;

import com.dtkq.api.entity.AskThumbs;
import java.util.List;

public interface AskThumbsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_thumbs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_thumbs
     *
     * @mbg.generated
     */
    int insert(AskThumbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_thumbs
     *
     * @mbg.generated
     */
    AskThumbs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_thumbs
     *
     * @mbg.generated
     */
    List<AskThumbs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask_thumbs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AskThumbs record);
}