package com.dtkq.api.mapper;

import com.dtkq.api.entity.AuthMenu;
import java.util.List;

public interface AuthMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated
     */
    int insert(AuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated
     */
    AuthMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated
     */
    List<AuthMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthMenu record);
}