package com.dtkq.api.mapper;

import com.dtkq.api.entity.BackMenu;
import java.util.List;

public interface BackMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table back_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table back_menu
     *
     * @mbg.generated
     */
    int insert(BackMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table back_menu
     *
     * @mbg.generated
     */
    BackMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table back_menu
     *
     * @mbg.generated
     */
    List<BackMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table back_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BackMenu record);
}