package com.dtkq.api.mapper;

import com.dtkq.api.entity.DoctorTimeBook;
import java.util.List;

public interface DoctorTimeBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_time_book
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_time_book
     *
     * @mbg.generated
     */
    int insert(DoctorTimeBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_time_book
     *
     * @mbg.generated
     */
    DoctorTimeBook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_time_book
     *
     * @mbg.generated
     */
    List<DoctorTimeBook> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_time_book
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DoctorTimeBook record);
}