package com.dtkq.api.mapper;

import com.dtkq.api.entity.DoctorTime;
import java.util.List;

public interface DoctorTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_time
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_time
     *
     * @mbg.generated
     */
    int insert(DoctorTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_time
     *
     * @mbg.generated
     */
    DoctorTime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_time
     *
     * @mbg.generated
     */
    List<DoctorTime> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DoctorTime record);
}