package com.dtkq.api.mapper;

import com.dtkq.api.entity.LinkDoctorClass;
import java.util.List;

public interface LinkDoctorClassMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_doctor_class
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_doctor_class
     *
     * @mbg.generated
     */
    int insert(LinkDoctorClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_doctor_class
     *
     * @mbg.generated
     */
    LinkDoctorClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_doctor_class
     *
     * @mbg.generated
     */
    List<LinkDoctorClass> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_doctor_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LinkDoctorClass record);
}