package com.dtkq.api.mapper;

import com.dtkq.api.entity.Subscribe;
import java.util.List;

public interface SubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated
     */
    int insert(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated
     */
    Subscribe selectByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated
     */
    List<Subscribe> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Subscribe record);
}