package com.dtkq.api.mapper;

import com.dtkq.api.entity.SysMsg;
import java.util.List;

public interface SysMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg
     *
     * @mbg.generated
     */
    int insert(SysMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg
     *
     * @mbg.generated
     */
    SysMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg
     *
     * @mbg.generated
     */
    List<SysMsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysMsg record);
}