package com.dtkq.api.mapper;

import com.dtkq.api.entity.UserTalkRead;
import java.util.List;

public interface UserTalkReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_talk_read
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_talk_read
     *
     * @mbg.generated
     */
    int insert(UserTalkRead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_talk_read
     *
     * @mbg.generated
     */
    UserTalkRead selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_talk_read
     *
     * @mbg.generated
     */
    List<UserTalkRead> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_talk_read
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserTalkRead record);
}